
export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_OPEN_AUTH = "MODAL_OPEN_AUTH";
export const MODAL_OPEN_TEACHER = "MODAL_OPEN_TEACHER";
export const MODAL_OPEN_LOGIN = "MODAL_OPEN_LOGIN";
export const MODAL_OPEN_REGISTER = "MODAL_OPEN_REGISTER";


export const TALK_SELECTED = "TALK_SELECTED";

export const TALK_FETCH_REQUESTED = "TALK_FETCH_REQUESTED";
export const TALK_FETCH_SUCCEEDED = "TALK_FETCH_SUCCEEDED";
export const TALK_FETCH_FAILED = "TALK_FETCH_FAILED";

export const TALK_ADD_REQUESTED = "TALK_ADD_REQUESTED";
export const TALK_ADD_SUCCEEDED = "TALK_ADD_SUCCEEDED";
export const TALK_ADD_FAILED = "TALK_ADD_FAILED";

export const TALK_UPDATE_REQUESTED = "TALK_UPDATE_REQUESTED";
export const TALK_UPDATE_SUCCEEDED = "TALK_UPDATE_SUCCEEDED";
export const TALK_UPDATE_FAILED = "TALK_UPDATE_FAILED";

export const TALK_DELETE_REQUESTED = "TALK_DELETE_REQUESTED";
export const TALK_DELETE_SUCCEEDED = "TALK_DELETE_SUCCEEDED";
export const TALK_DELETE_FAILED = "TALK_DELETE_FAILED";

export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_REQUESTED_SUCCEEDED = "LOGIN_REQUESTED_SUCCEEDED";
export const LOGIN_REQUESTED_FAILED = "LOGIN_REQUESTED_FAILED";

export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_REQUESTED_SUCCEEDED = "LOGOUT_REQUESTED_SUCCEEDED";
export const LOGOUT_REQUESTED_FAILED = "LOGOUT_REQUESTED_FAILED";

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';

export const STUDENT_SELECTED = "STUDENT_SELECTED";
export const STUDENT_FETCH_REQUESTED = "STUDENT_FETCH_REQUESTED";
export const STUDENT_FETCH_SUCCEEDED = "STUDENT_FETCH_SUCCEEDED";
export const STUDENT_FETCH_FAILED = "STUDENT_FETCH_FAILED";

export const STUDENT_ADD_REQUESTED = "STUDENT_ADD_REQUESTED";
export const STUDENT_ADD_SUCCEEDED = "STUDENT_ADD_SUCCEEDED";
export const STUDENT_ADD_FAILED = "STUDENT_ADD_FAILED";

export const STUDENT_UPDATE_REQUESTED = "STUDENT_UPDATE_REQUESTED";
export const STUDENT_UPDATE_SUCCEEDED = "STUDENT_UPDATE_SUCCEEDED";
export const STUDENT_UPDATE_FAILED = "STUDENT_UPDATE_FAILED";

export const STUDENT_DELETE_REQUESTED = "STUDENT_DELETE_REQUESTED";
export const STUDENT_DELETE_SUCCEEDED = "STUDENT_DELETE_SUCCEEDED";
export const STUDENT_DELETE_FAILED = "STUDENT_DELETE_FAILED";





export const TEACHER_SELECTED = "TEACHER_SELECTED";

export const TEACHER_FETCH_REQUESTED = "TEACHER_FETCH_REQUESTED";
export const TEACHER_FETCH_SUCCEEDED = "TEACHER_FETCH_SUCCEEDED";
export const TEACHER_FETCH_FAILED = "TEACHER_FETCH_FAILED";

export const TEACHER_ADD_REQUESTED = "TEACHER_ADD_REQUESTED";
export const TEACHER_ADD_SUCCEEDED = "TEACHER_ADD_SUCCEEDED";
export const TEACHER_ADD_FAILED = "TEACHER_ADD_FAILED";

export const TEACHER_UPDATE_REQUESTED = "TEACHER_UPDATE_REQUESTED";
export const TEACHER_UPDATE_SUCCEEDED = "TEACHER_UPDATE_SUCCEEDED";
export const TEACHER_UPDATE_FAILED = "TEACHER_UPDATE_FAILED";

export const TEACHER_DELETE_REQUESTED = "TEACHER_DELETE_REQUESTED";
export const TEACHER_DELETE_SUCCEEDED = "TEACHER_DELETE_SUCCEEDED";
export const TEACHER_DELETE_FAILED = "TEACHER_DELETE_FAILED";

export const TEACHER_SYNC_REQUESTED = "TEACHER_SYNC_REQUESTED";
export const TEACHER_SYNC_SUCCEEDED = "TEACHER_SYNC_SUCCEEDED";
export const TEACHER_SYNC_FAILED = "TEACHER_SYNC_FAILED";

export const VIDEOLOG_SELECTED = "VIDEOLOG_SELECTED";

export const VIDEOLOG_FETCH_REQUESTED = "VIDEOLOG_FETCH_REQUESTED";
export const VIDEOLOG_FETCH_SUCCEEDED = "VIDEOLOG_FETCH_SUCCEEDED";
export const VIDEOLOG_FETCH_FAILED = "VIDEOLOG_FETCH_FAILED";

export const VIDEOLOG_ADD_REQUESTED = "VIDEOLOG_ADD_REQUESTED";
export const VIDEOLOG_ADD_SUCCEEDED = "VIDEOLOG_ADD_SUCCEEDED";
export const VIDEOLOG_ADD_FAILED = "VIDEOLOG_ADD_FAILED";

export const VIDEOLOG_UPDATE_REQUESTED = "VIDEOLOG_UPDATE_REQUESTED";
export const VIDEOLOG_UPDATE_SUCCEEDED = "VIDEOLOG_UPDATE_SUCCEEDED";
export const VIDEOLOG_UPDATE_FAILED = "VIDEOLOG_UPDATE_FAILED";

export const VIDEOLOG_DELETE_REQUESTED = "VIDEOLOG_DELETE_REQUESTED";
export const VIDEOLOG_DELETE_SUCCEEDED = "VIDEOLOG_DELETE_SUCCEEDED";
export const VIDEOLOG_DELETE_FAILED = "VIDEOLOG_DELETE_FAILED";